apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
  namespace: "{{ .Values.namespace }}"
spec:
  tls:
    - hosts:
      {{- range .Values.hosts }}
      - {{ . }}
      {{- end }}
      secretName: frontend-ingress-tls
  rules:
    {{- range .Values.hosts }}
    - host: {{ . }}
      http:
        paths:
        - backend:
            service:
              name: frontend-service
              port:
                number: 80
          path: /
          pathType: Exact
    {{- end }}